## Removing Reinvestments and Wire transactions

In [2]:
import pandas as pd

In [4]:
 df= pd.read_csv('/Users/ludwingmoncadabellorin/code/Malvinrud/aml_detector/raw_data/new_hi_small_trans.csv')

In [5]:
df.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,Year,Month,Day,Hour,Minute,Currency Code,Rate,Amount Paid USD,Amount Received USD
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0,2022,9,1,0,20,USD,1.0,3697.34,3697.34
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0,2022,9,1,0,20,USD,1.0,0.01,0.01
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0,2022,9,1,0,0,USD,1.0,14675.57,14675.57
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0,2022,9,1,0,2,USD,1.0,2806.97,2806.97
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0,2022,9,1,0,6,USD,1.0,36682.97,36682.97

In [6]:
# Identify Unique Payment Format 
unique_currencies = df['Payment Format'].unique()
print(unique_currencies)

['Reinvestment' 'Cheque' 'Credit Card' 'ACH' 'Cash' 'Wire' 'Bitcoin']

In [13]:
# Get the total count of each payment format
payment_format_counts = df['Payment Format'].value_counts()

# Calculate the percentages
payment_format_percentages = payment_format_counts / len(df) * 100

# Get the counts of laundering and non-laundering transactions for each payment format
laundering_counts = df[df['Is Laundering'] == 1]['Payment Format'].value_counts()
non_laundering_counts = df[df['Is Laundering'] == 0]['Payment Format'].value_counts()

# Calculate the percentages
laundering_percentages = laundering_counts / payment_format_counts * 100
non_laundering_percentages = non_laundering_counts / payment_format_counts * 100

# Display the counts and percentages side by side
df_counts_percentages = pd.DataFrame({
    'Count': payment_format_counts,
    'Percentage of Total': payment_format_percentages,
    'Laundering Count': laundering_counts,
    'Laundering Percentage': laundering_percentages,
    'Non-Laundering Count': non_laundering_counts,
    'Non-Laundering Percentage': non_laundering_percentages
})
df_counts_percentages

,Count,Percentage of Total,Laundering Count,Laundering Percentage,Non-Laundering Count,Non-Laundering Percentage
Payment Format,,,,,,
ACH,600797,11.830567,4483.0,0.746175,596314,99.253825
Bitcoin,146091,2.876744,56.0,0.038332,146035,99.961668
Cash,490891,9.666358,108.0,0.022001,490783,99.977999
Cheque,1864331,36.711389,324.0,0.017379,1864007,99.982621
Credit Card,1323324,26.058174,206.0,0.015567,1323118,99.984433
Reinvestment,481056,9.472692,NaN,NaN,481056,100.000000
Wire,171855,3.384075,NaN,NaN,171855,100.000000

1) Reinvestment represents only 9% of the dataset and non of them is laundering
2) Wire only represents 3% of the dataset and non of them is laundering.
**Proceeding to delete them**

In [15]:
# List of payment formats to remove
remove_formats = ['Reinvestment', 'Wire']

# Remove the rows with the specified payment formats
df = df[~df['Payment Format'].isin(remove_formats)]

In [16]:
#Re run everything for good measure ;)

# Get the total count of each payment format
payment_format_counts = df['Payment Format'].value_counts()

# Calculate the percentages
payment_format_percentages = payment_format_counts / len(df) * 100

# Get the counts of laundering and non-laundering transactions for each payment format
laundering_counts = df[df['Is Laundering'] == 1]['Payment Format'].value_counts()
non_laundering_counts = df[df['Is Laundering'] == 0]['Payment Format'].value_counts()

# Calculate the percentages
laundering_percentages = laundering_counts / payment_format_counts * 100
non_laundering_percentages = non_laundering_counts / payment_format_counts * 100

# Display the counts and percentages side by side
df_counts_percentages = pd.DataFrame({
    'Count': payment_format_counts,
    'Percentage of Total': payment_format_percentages,
    'Laundering Count': laundering_counts,
    'Laundering Percentage': laundering_percentages,
    'Non-Laundering Count': non_laundering_counts,
    'Non-Laundering Percentage': non_laundering_percentages
})
df_counts_percentages

,Count,Percentage of Total,Laundering Count,Laundering Percentage,Non-Laundering Count,Non-Laundering Percentage
Payment Format,,,,,,
ACH,600797,13.576002,4483,0.746175,596314,99.253825
Bitcoin,146091,3.301168,56,0.038332,146035,99.961668
Cash,490891,11.092494,108,0.022001,490783,99.977999
Cheque,1864331,42.127642,324,0.017379,1864007,99.982621
Credit Card,1323324,29.902694,206,0.015567,1323118,99.984433